backend:
  name: github
  repo: "jshuntley/gilabrewco"
  branch: main
  base_url: "https://decap.gilabrewco.com"

site_url: "https://gilabrewco.com"
local_backend: true

# Cloudflare Pages specific configuration
display_url: "https://gilabrewco.com"
logo_url: "/assets/images/logo.png"

publish_mode: editorial_workflow

# Preview configuration
site_domain: gilabrewco.pages.dev
preview_path: "blog/{{slug}}"
preview_path_date_field: "publishDate"

media_folder: "public/assets/images/"
public_folder: "/assets/images/"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "PublishDate", name: "publishDate", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false,
          media_folder: "/assets/blog",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          required: false,
          allow_add: true,
          default: [],
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "brews"
    label: "Brews"
    folder: "src/content/brews"
    create: true
    extension: "json"
    format: "json"
    identifier_field: "id"
    slug: "{{id}}"
    summary: "{{name}} - {{style}}"
    fields:
      - {
          label: "ID",
          name: "id",
          widget: "string",
          pattern:
            [
              "^[a-z0-9-]+$",
              "Must be lowercase letters, numbers, and hyphens only",
            ],
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Style", name: "style", widget: "string" }
      - {
          label: "ABV",
          name: "abv",
          widget: "number",
          value_type: "float",
          min: 0,
          max: 20,
          step: 0.1,
        }
      - {
          label: "Status",
          name: "status",
          widget: "select",
          options:
            [
              "upcoming",
              "waiting for ingredients",
              "fermenting",
              "soft crashing",
              "crashing",
              "secondary fermentation",
              "conditioning",
              "carbonating",
              "kegged",
              "on tap",
              "gone",
            ],
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Details", name: "details", widget: "string" }
      - { label: "Notes", name: "notes", widget: "text", required: false }
      - {
          label: "Brewfather ID",
          name: "brewfatherId",
          widget: "string",
          required: false,
        }
